# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swinx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swinx

  target 'SwinxTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
